import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "react-router-dom";
import {
  answerSellerInquiry, createSellerProduct, createSellerVariant, deleteSellerProduct,
  getCategories, getSellerDashboard, getSellerInquiries, getSellerOrders, getSellerProducts,
  getSellerReviews, getSellerSettlement, updateSellerProduct, updateSellerShippingStatus,
  updateSellerVariant,
} from "../api/shopApi";
import "./Center.css";

const money=v=>`${Number(v||0).toLocaleString("ko-KR")}원`;
const statusText={PAID:"결제완료",PREPARING:"상품준비중",SHIPPING:"배송중",DELIVERED:"배송완료",COMPLETED:"구매완료"};
const tabs=[["dashboard","▦","대시보드"],["products","📦","상품·재고"],["orders","🚚","주문·배송"],["settlement","₩","정산"],["cs","💬","고객문의"],["reviews","★","구매리뷰"]];

function SellerCenter(){
  const [params,setParams]=useSearchParams(); const tab=params.get("tab")||"dashboard";
  const [data,setData]=useState(null); const [categories,setCategories]=useState([]); const [loading,setLoading]=useState(true);
  const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const [keyword,setKeyword]=useState("");
  async function load(){setLoading(true);setError("");try{const loaders={dashboard:getSellerDashboard,products:getSellerProducts,orders:getSellerOrders,settlement:getSellerSettlement,cs:getSellerInquiries,reviews:getSellerReviews};const [result,cats]=await Promise.all([loaders[tab](),getCategories()]);setData(result);setCategories(cats.items||[]);}catch(e){setError(e.message)}finally{setLoading(false)}}
  useEffect(()=>{load()},[tab]);
  async function action(fn){try{setError("");const r=await fn();setNotice(r?.message||"처리되었습니다.");await load()}catch(e){setError(e.message)}}
  return <div className="center-page"><aside className="center-side"><h2>SELLER CENTER</h2><p>내 상품과 주문 운영</p>{tabs.map(([v,i,l])=><button key={v} className={tab===v?"is-active":""} onClick={()=>setParams({tab:v})}><span>{i}</span>{l}</button>)}</aside><section className="center-main"><div className="center-title"><div><span>SELLER ADMIN</span><h1>판매자 센터</h1><p>내 상품, 재고, 주문, 배송, 정산과 고객 문의를 관리합니다.</p></div><button className="center-button" onClick={load}>↻ 새로고침</button></div>{notice&&<div className="center-notice center-notice--success">✓ {notice}</div>}{error&&<div className="center-notice center-notice--error">{error}</div>}{loading?<div className="shop-state">판매자 데이터를 불러오는 중입니다...</div>:<>{tab==="dashboard"&&<SellerDashboard data={data}/>} {tab==="products"&&<SellerProducts data={data} categories={categories} keyword={keyword} setKeyword={setKeyword} action={action}/>} {tab==="orders"&&<SellerOrders data={data} action={action}/>} {tab==="settlement"&&<Settlement data={data}/>} {tab==="cs"&&<CS data={data} action={action}/>} {tab==="reviews"&&<Reviews data={data}/>}</>}</section></div>
}

function SellerDashboard({data}){
  const s=data?.summary||{};
  const trend=data?.sales_trend||[];
  const maxSales=Math.max(1,...trend.map(i=>Number(i.sales||0)));
  return <>
    <div className="center-grid">
      <div className="center-card"><small>오늘 판매완료 매출</small><strong>{money(s.today_sales)}</strong></div>
      <div className="center-card"><small>이번 달 매출</small><strong>{money(s.month_sales)}</strong></div>
      <div className="center-card"><small>내 판매 상품</small><strong>{s.product_count||0}개</strong></div>
      <div className={`center-card ${Number(s.low_stock_variants||0)>0?"center-card--warning":""}`}><small>재고 부족 옵션</small><strong>{s.low_stock_variants||0}개</strong></div>
      <div className="center-card"><small>결제완료 주문</small><strong>{s.paid_orders||0}건</strong></div>
      <div className="center-card"><small>상품준비중</small><strong>{s.preparing_orders||0}건</strong></div>
      <div className="center-card"><small>배송중</small><strong>{s.shipping_orders||0}건</strong></div>
      <div className="center-card"><small>미답변 문의</small><strong>{s.pending_inquiries||0}건</strong></div>
    </div>
    <div className="center-panel">
      <h2>최근 7일 판매완료 매출</h2>
      <div className="center-chart">
        {trend.map(row=><div className="center-chart__item" key={row.label}><div className="center-chart__value">{money(row.sales)}</div><div className="center-chart__bar-wrap"><div className="center-chart__bar" style={{height:`${Math.max(4,Math.round(Number(row.sales||0)/maxSales*100))}%`}}/></div><div className="center-chart__label">{row.label}</div></div>)}
      </div>
    </div>
    {(data?.low_stock||[]).length>0&&<div className="center-panel"><h2>⚠ 재고 부족 알림</h2><div className="center-table-wrap"><table className="center-table"><thead><tr><th>상품</th><th>SKU</th><th>가용재고</th><th>안전재고</th></tr></thead><tbody>{data.low_stock.map(i=><tr key={i.variant_id}><td><b>{i.product_name}</b></td><td>{i.sku_code}</td><td><span className="center-status center-status--red">{i.available_stock}</span></td><td>{i.safety_stock}</td></tr>)}</tbody></table></div></div>}
    <div className="center-panel"><h2>최근 내 상품 주문</h2><div className="center-table-wrap"><table className="center-table"><thead><tr><th>주문</th><th>구매자</th><th>상품</th><th>내 판매금액</th><th>상태</th></tr></thead><tbody>{(data?.recent_orders||[]).map(o=><tr key={o.order_id}><td><b>{o.order_no}</b></td><td>{o.buyer_name}</td><td>{o.product_names}</td><td>{money(o.seller_amount)}</td><td>{o.item_statuses}</td></tr>)}</tbody></table></div></div>
  </>;
}
function SellerProducts({data,categories,keyword,setKeyword,action}){
 const [showForm,setShowForm]=useState(false); const [form,setForm]=useState({category_id:"",product_name:"",short_description:"",description:"",regular_price:"",sale_price:"",product_status:"READY",sku_code:"",option_name1:"Color",option_value1:"Default",option_name2:"",option_value2:"",additional_price:0,stock_quantity:0,safety_stock:0});
 const list=useMemo(()=>{const q=keyword.trim().toLowerCase();return (data?.items||[]).filter(p=>!q||`${p.product_name} ${p.product_code} ${p.category_name}`.toLowerCase().includes(q))},[data,keyword]);
 async function submit(e){e.preventDefault();await action(()=>createSellerProduct({...form,category_id:Number(form.category_id),regular_price:Number(form.regular_price),sale_price:Number(form.sale_price),additional_price:Number(form.additional_price||0),stock_quantity:Number(form.stock_quantity||0),safety_stock:Number(form.safety_stock||0)}));setShowForm(false)}
 return <><div className="center-panel"><div className="center-toolbar"><input value={keyword} onChange={e=>setKeyword(e.target.value)} placeholder="내 상품 검색"/><button className="center-button center-button--primary" onClick={()=>setShowForm(!showForm)}>+ 상품 등록</button></div>{showForm&&<form className="center-form" onSubmit={submit}><label>카테고리<select required value={form.category_id} onChange={e=>setForm({...form,category_id:e.target.value})}><option value="">선택</option>{categories.filter(c=>c.active_yn!=="N").map(c=><option key={c.category_id} value={c.category_id}>{c.category_name}</option>)}</select></label><label>상품명<input required value={form.product_name} onChange={e=>setForm({...form,product_name:e.target.value})}/></label><label>정상가<input required type="number" min="0" value={form.regular_price} onChange={e=>setForm({...form,regular_price:e.target.value})}/></label><label>판매가<input required type="number" min="0" value={form.sale_price} onChange={e=>setForm({...form,sale_price:e.target.value})}/></label><label>SKU<input value={form.sku_code} onChange={e=>setForm({...form,sku_code:e.target.value})} placeholder="비우면 자동 생성"/></label><label>초기 재고<input type="number" min="0" value={form.stock_quantity} onChange={e=>setForm({...form,stock_quantity:e.target.value})}/></label><label>옵션명<input value={form.option_name1} onChange={e=>setForm({...form,option_name1:e.target.value})}/></label><label>옵션값<input value={form.option_value1} onChange={e=>setForm({...form,option_value1:e.target.value})}/></label><label className="full">짧은 소개<input value={form.short_description} onChange={e=>setForm({...form,short_description:e.target.value})}/></label><label className="full">상세 설명<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="center-form-actions"><button type="button" className="center-button" onClick={()=>setShowForm(false)}>취소</button><button className="center-button center-button--primary">등록</button></div></form>}</div><div className="center-panel"><h2>내 상품 · 옵션 · 재고</h2>{list.map(p=><ProductEditor key={p.product_id} p={p} categories={categories} action={action}/>)}</div></>}
function ProductEditor({p,action}){const [name,setName]=useState(p.product_name);const [sale,setSale]=useState(p.sale_price);const [status,setStatus]=useState(p.product_status);const [variantForm,setVariantForm]=useState({sku_code:"",option_name1:"",option_value1:"",option_name2:"",option_value2:"",additional_price:0,stock_quantity:0,safety_stock:0});const [showVariant,setShowVariant]=useState(false);return <div className="center-product"><div className="center-product__head"><div><h3>{p.product_name}</h3><div className="center-product__meta">{p.product_code} · {p.category_name} · 정상가 {money(p.regular_price)}</div></div><button className="center-button center-button--danger" onClick={()=>window.confirm("상품을 판매 목록에서 삭제할까요?")&&action(()=>deleteSellerProduct(p.product_id))}>삭제</button></div><div className="center-variant"><input value={name} onChange={e=>setName(e.target.value)}/><input type="number" value={sale} onChange={e=>setSale(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value)}><option>READY</option><option>SALE</option><option>SOLD_OUT</option><option>STOPPED</option></select><button onClick={()=>action(()=>updateSellerProduct(p.product_id,{product_name:name,sale_price:Number(sale),product_status:status}))}>상품 저장</button></div>{(p.variants||[]).map(v=><VariantEditor key={v.variant_id} v={v} action={action}/>) }<button className="center-button" onClick={()=>setShowVariant(!showVariant)}>+ 옵션 추가</button>{showVariant&&<form className="center-form" style={{marginTop:12}} onSubmit={e=>{e.preventDefault();action(()=>createSellerVariant(p.product_id,{...variantForm,additional_price:Number(variantForm.additional_price||0),stock_quantity:Number(variantForm.stock_quantity||0),safety_stock:Number(variantForm.safety_stock||0)}));setShowVariant(false)}}><label>SKU<input required value={variantForm.sku_code} onChange={e=>setVariantForm({...variantForm,sku_code:e.target.value})}/></label><label>재고<input type="number" min="0" value={variantForm.stock_quantity} onChange={e=>setVariantForm({...variantForm,stock_quantity:e.target.value})}/></label><label>옵션명 1<input value={variantForm.option_name1} onChange={e=>setVariantForm({...variantForm,option_name1:e.target.value})}/></label><label>옵션값 1<input value={variantForm.option_value1} onChange={e=>setVariantForm({...variantForm,option_value1:e.target.value})}/></label><div className="center-form-actions"><button className="center-button center-button--primary">옵션 등록</button></div></form>}</div>}
function VariantEditor({v,action}){const [stock,setStock]=useState(v.stock_quantity);const [safety,setSafety]=useState(v.safety_stock);const label=[v.option_name1&&`${v.option_name1}: ${v.option_value1}`,v.option_name2&&`${v.option_name2}: ${v.option_value2}`].filter(Boolean).join(" / ")||"기본 옵션";const available=Math.max(0,Number(stock||0)-Number(v.reserved_quantity||0));const low=available<=Number(safety||0);return <div className={`center-variant ${low?"is-low-stock":""}`}><div><b>{label}</b><small>{v.sku_code}{low?` · ⚠ 가용재고 ${available}`:""}</small></div><label>재고 <input type="number" min="0" value={stock} onChange={e=>setStock(e.target.value)}/></label><label>안전재고 <input type="number" min="0" value={safety} onChange={e=>setSafety(e.target.value)}/></label><button onClick={()=>action(()=>updateSellerVariant(v.variant_id,{stock_quantity:Number(stock),safety_stock:Number(safety)}))}>재고 저장</button></div>}

function SellerOrders({data,action}){const [filter,setFilter]=useState("ALL");const [keyword,setKeyword]=useState("");const q=keyword.trim().toLowerCase();const list=(data?.items||[]).filter(o=>{if(filter!=="ALL"&&o.seller_status!==filter)return false;if(!q)return true;return [o.order_no,o.buyer_name,o.buyer_login_id,o.receiver_name,o.receiver_phone,o.shipping_address1,...(o.items||[]).map(i=>i.product_name_snapshot)].filter(Boolean).join(" ").toLowerCase().includes(q)});return <><div className="center-panel"><div className="center-toolbar"><div>{["ALL","PAID","PREPARING","SHIPPING","DELIVERED","COMPLETED"].map(s=><button key={s} className="center-button" style={{marginRight:6}} onClick={()=>setFilter(s)}>{s==="ALL"?"전체":statusText[s]}{s!=="ALL"?` ${data?.counts?.[s]||0}`:""}</button>)}</div><b>{list.length}건</b></div><div className="center-toolbar"><input value={keyword} onChange={e=>setKeyword(e.target.value)} placeholder="주문번호, 구매자, 상품명, 배송지 검색"/><span className="center-kicker">내 상품 주문만 검색합니다.</span></div></div>{list.length?list.map(o=><SellerOrder key={o.order_id} o={o} action={action}/>):<div className="center-empty">조건에 맞는 주문이 없습니다.</div>}</>}
function SellerOrder({o,action}){const next={PAID:"PREPARING",PREPARING:"SHIPPING",SHIPPING:"DELIVERED"}[o.seller_status];return <div className="center-order"><div className="center-order__head"><div><b>{o.order_no}</b><small>{o.buyer_name} ({o.buyer_login_id})</small></div><span className="center-status">{statusText[o.seller_status]||o.seller_status}</span></div><div className="center-order__items">{o.items.map(i=><div className="center-order__item" key={i.order_item_id}><span>{i.product_name_snapshot} · {i.sku_snapshot} · {i.quantity}개</span><b>{money(i.item_amount)} · {statusText[i.item_status]||i.item_status}</b></div>)}</div><div className="center-kicker">배송지: [{o.zipcode||""}] {o.shipping_address1} {o.shipping_address2} / {o.receiver_name} {o.receiver_phone}</div><div className="center-order__actions"><b>내 주문금액 {money(o.seller_amount)}</b>{next&&<button className="center-button center-button--primary" onClick={()=>window.confirm(`${statusText[next]} 상태로 변경할까요?`)&&action(()=>updateSellerShippingStatus(o.order_id,next))}>{statusText[next]} 처리</button>}{o.seller_status==="DELIVERED"&&<span className="center-status center-status--green">배송완료</span>}</div></div>}

function Settlement({data}){const s=data?.summary||{};const p=data?.seller_profile||{};return <>
  <div className="center-grid"><div className="center-card"><small>오늘 판매완료</small><strong>{money(s.today_amount)}</strong></div><div className="center-card"><small>이번 달 판매완료</small><strong>{money(s.this_month_amount)}</strong></div><div className="center-card"><small>정산 대상 누적매출</small><strong>{money(s.settlement_target_amount)}</strong></div><div className="center-card"><small>정산 계좌</small><strong style={{fontSize:16}}>{p.settlement_bank||"미등록"}</strong><small>{p.settlement_account||"-"}</small></div></div>
  <div className="center-warning">{data?.notice}</div>
  <div className="center-panel"><h2>상품별 판매 매출 TOP 10</h2><div className="center-table-wrap"><table className="center-table"><thead><tr><th>순위</th><th>상품</th><th>판매수량</th><th>판매완료 매출</th></tr></thead><tbody>{(data?.top_products||[]).map((i,idx)=><tr key={i.product_id}><td><b>{idx+1}</b></td><td>{i.product_name}</td><td>{i.sold_quantity}개</td><td><b>{money(i.sales_amount)}</b></td></tr>)}</tbody></table></div></div>
  <div className="center-panel"><h2>판매완료 내역</h2><div className="center-table-wrap"><table className="center-table"><thead><tr><th>주문번호</th><th>상품</th><th>수량</th><th>금액</th><th>상태</th></tr></thead><tbody>{(data?.items||[]).map((i,idx)=><tr key={`${i.order_no}-${idx}`}><td>{i.order_no}</td><td>{i.product_name_snapshot}</td><td>{i.quantity}</td><td>{money(i.item_amount)}</td><td>{statusText[i.item_status]}</td></tr>)}</tbody></table></div></div>
</>;}
function CS({data,action}){const [answers,setAnswers]=useState({});return <div className="center-panel"><h2>고객 문의</h2>{(data?.items||[]).map(i=><div className="center-product" key={i.inquiry_id}><div className="center-product__head"><div><b>[{i.category_code}] {i.title}</b><div className="center-product__meta">{i.buyer_name} · {String(i.created_at).slice(0,16).replace("T"," ")}</div></div><span className="center-status">{i.inquiry_status}</span></div><p>{i.content}</p>{i.answer_content?<div className="center-answer"><b>답변</b><br/>{i.answer_content}</div>:<div className="center-answer-box"><textarea value={answers[i.inquiry_id]||""} onChange={e=>setAnswers({...answers,[i.inquiry_id]:e.target.value})} placeholder="고객에게 보낼 답변을 입력하세요"/><button className="center-button center-button--primary" onClick={()=>action(()=>answerSellerInquiry(i.inquiry_id,answers[i.inquiry_id]||""))}>답변 등록</button></div>}</div>)}</div>}
function Reviews({data}){return <div className="center-panel"><h2>내 상품 구매리뷰</h2>{(data?.items||[]).map(r=><div className="center-product" key={r.review_id}><div className="center-product__head"><div><b>{r.product_name}</b><div className="center-review-stars">{"★".repeat(Number(r.rating||0))}{"☆".repeat(5-Number(r.rating||0))}</div></div><small>{r.buyer_name} · {String(r.added_at).slice(0,10)}</small></div><p>{r.review_txt}</p></div>)}</div>}

export default SellerCenter;
